### ISSUE TITLE
你好，想问下这个错误怎么解决

### ISSUE THREAD

**Issue by 1s23** [xialuxi/yolov5-car-plate#5]
![image](https://user-images.githubusercontent.com/52626440/123752115-1bc8f100-d8eb-11eb-842b-3ff6fa4648df.png)
我把它改成下面这样
![image](https://user-images.githubusercontent.com/52626440/123752281-38652900-d8eb-11eb-8135-b0fd879f5f30.png)

但还会报错，报如下错
![image](https://user-images.githubusercontent.com/52626440/123752564-7c582e00-d8eb-11eb-90c7-ea4a197bf458.png)
我数据集的lable是13个：1（类别）+4（x,y,w,h)+8（四个点的）

**Comment by liuxiaoxiao666** [comment]
你好 有数据集吗

**Comment by 1s23** [comment]
> 你好 有数据集吗

我用的是就是CCPD的数据集

**Comment by Dujianhua1008** [comment]
也是报这个错,py3.7 torch1.7 ,问题解决了吗

**Comment by CompliceU** [comment]
@1s23 你好，不知道你解决了这个问题了吗？我也卡在了这里，测试就报错

**Comment by 1s23** [comment]
> @1s23 你好，不知道你解决了这个问题了吗？我也卡在了这里，测试就报错



> 也是报这个错,py3.7 torch1.7 ,问题解决了吗
改成这样就行
![截图_20214511114555](https://user-images.githubusercontent.com/52626440/128966438-e6406a31-7f1a-4372-abdc-d8a36cee1256.png)

**Comment by CompliceU** [comment]
@1s23  你好，我改完后，又在测试部分出现这个问题
![image](https://user-images.githubusercontent.com/24600457/128968540-516cba71-1389-40f4-9da1-52ad27580131.png)
不知道你有遇到吗

**Comment by 1s23** [comment]
> @1s23 你好，我改完后，又在测试部分出现这个问题
> ![image](https://user-images.githubusercontent.com/24600457/128968540-516cba71-1389-40f4-9da1-52ad27580131.png)
> 不知道你有遇到吗

![image](https://user-images.githubusercontent.com/52626440/129704288-89e024b5-0b10-4287-b9c5-c84522a1058f.png)
这张图里 ，我是把
labels = np.hstack((labels,landmarks))
注释掉了呢！！

**Comment by CompliceU** [comment]
@1s23 我是在前面对landmark做一次重排，在前面label重排的地方，也能训练，但是效果不是很好

**Comment by 1s23** [comment]
> @1s23 我是在前面对landmark做一次重排，在前面label重排的地方，也能训练，但是效果不是很好

呃呃，我也不是很清楚哈，我训练起来效果还可以

**Comment by CompliceU** [comment]
@1s23 我来试试，可以加个联系方式不
